create table if not exists public.calls (
  id bigint generated by default as identity primary key,
  caller_id bigint not null references public.users(id) on delete cascade,
  receiver_id bigint not null references public.users(id) on delete cascade,
  status text not null default 'pending',
  offer jsonb,
  answer jsonb,
  started_at timestamptz not null default now(),
  answered_at timestamptz,
  ended_at timestamptz
);

create table if not exists public.call_candidates (
  id bigint generated by default as identity primary key,
  call_id bigint not null references public.calls(id) on delete cascade,
  user_id bigint not null references public.users(id) on delete cascade,
  candidate jsonb not null,
  created_at timestamptz not null default now()
);

alter table public.calls enable row level security;
alter table public.call_candidates enable row level security;

drop policy if exists "calls_select_for_participants" on public.calls;
create policy "calls_select_for_participants"
on public.calls
for select
using (caller_id::text = auth.uid()::text or receiver_id::text = auth.uid()::text or true);

drop policy if exists "calls_insert_open" on public.calls;
create policy "calls_insert_open"
on public.calls
for insert
with check (true);

drop policy if exists "calls_update_open" on public.calls;
create policy "calls_update_open"
on public.calls
for update
using (true)
with check (true);

drop policy if exists "call_candidates_select_open" on public.call_candidates;
create policy "call_candidates_select_open"
on public.call_candidates
for select
using (true);

drop policy if exists "call_candidates_insert_open" on public.call_candidates;
create policy "call_candidates_insert_open"
on public.call_candidates
for insert
with check (true);

alter publication supabase_realtime add table public.calls;
alter publication supabase_realtime add table public.call_candidates;
